<?php
declare(strict_types=1);
require_once __DIR__ . '/db.php'; require_once __DIR__ . '/http.php'; require_once __DIR__ . '/activity_qr_token.php';
try {
 $pdo=db(); $user=requireUser($pdo); $action=$_GET['action']??'list'; $in=requestInput();
 if($action==='list') { $s=$pdo->query("SELECT a.*, a.activity_date AS date, a.start_time AS startTime, a.end_time AS endTime, a.venue_address AS venueAddress, a.generate_qr AS generateQr, a.deadline_date AS deadlineDate, a.deadline_time AS deadlineTime, a.academic_year AS academicYear, COALESCE((SELECT COUNT(*) FROM activity_attendance x WHERE x.activity_id=a.id),0) AS participantCount FROM activities a ORDER BY a.activity_date DESC,a.id DESC"); jsonResponse(true,'',200,['activities'=>$s->fetchAll()]); }
 if($action==='create') { requireUser($pdo,['ADMIN','REPRESENTATIVE']); $name=trim((string)($in['name']??'')); if($name==='') jsonResponse(false,'Activity name is required.',422); $type=trim((string)($in['type']??''));if(!in_array($type,['Municipal Activity','Alternative Activity'],true))jsonResponse(false,'Choose Municipal Activity or Alternative Activity.',422); $mode=strtolower(trim((string)($in['generateQr']??'')));if(!in_array($mode,['qr','proof','both'],true))jsonResponse(false,'Choose QR code, proof submission, or both.',422); $descriptionImage=trim((string)($in['descriptionImage']??''));if($descriptionImage!==''){if(strlen($descriptionImage)>3*1024*1024||!preg_match('#\Adata:image/(?:jpeg|png|webp);base64,([A-Za-z0-9+/]+={0,2})\z#',$descriptionImage,$imageMatch))jsonResponse(false,'Upload a JPG, PNG, or WebP image up to 2 MB.',422);$imageBytes=base64_decode($imageMatch[1],true);if($imageBytes===false||strlen($imageBytes)>2*1024*1024)jsonResponse(false,'Upload a JPG, PNG, or WebP image up to 2 MB.',422);} $cols=['name','type','activity_date','start_time','end_time','venue','venue_address','generate_qr','deadline_date','deadline_time','academic_year','semester','description','description_image','municipality','barangay','created_by']; $vals=[$name,$type,$in['date']??'',$in['startTime']??'',$in['endTime']??'',$in['venue']??'',$in['venueAddress']??'',$mode,$in['deadlineDate']??'',$in['deadlineTime']??'',$in['academicYear']??'',$in['semester']??'',$in['description']??'',$descriptionImage,$in['municipality']??'',$in['barangay']??'',$user['id']];
  $s=$pdo->prepare('INSERT INTO activities('.implode(',',$cols).') VALUES('.implode(',',array_fill(0,count($cols),'?')).')'); $s->execute($vals); $activityId=(int)$pdo->lastInsertId();$notice=$pdo->prepare("INSERT INTO notifications(user_id,type,title,message,activity_id) SELECT id,'new_activity','A new activity appeared!',?,? FROM users WHERE UPPER(status)='ACTIVE'");$notice->execute([$name,$activityId]);if(in_array($mode,['qr','both'],true)){$users=$pdo->query("SELECT id FROM users WHERE status='ACTIVE'")->fetchAll(PDO::FETCH_COLUMN);foreach($users as $participantId)activityQrToken($pdo,$activityId,(int)$participantId);}jsonResponse(true,'Activity created and individual participant QR codes are ready.',201,['id'=>$activityId]); }
 if($action==='get') { $id=(int)($in['id']??$_GET['id']??0); if(!$id) jsonResponse(false,'Invalid activity.',422); $s=$pdo->prepare('SELECT *,activity_date AS date,start_time AS startTime,end_time AS endTime,venue_address AS venueAddress,generate_qr AS generateQr,deadline_date AS deadlineDate,deadline_time AS deadlineTime,academic_year AS academicYear FROM activities WHERE id=?');$s->execute([$id]);$a=$s->fetch();if(!$a)jsonResponse(false,'Activity not found.',404);jsonResponse(true,'',200,['activity'=>$a]); }
 if($action==='update') { requireUser($pdo,['ADMIN','REPRESENTATIVE']);$id=(int)($in['id']??0);if(!$id)jsonResponse(false,'Invalid activity.',422);$existing=$pdo->prepare('SELECT description_image FROM activities WHERE id=?');$existing->execute([$id]);$oldImage=$existing->fetchColumn();if($oldImage===false)jsonResponse(false,'Activity not found.',404);$name=trim((string)($in['name']??''));if($name==='')jsonResponse(false,'Activity name is required.',422);$type=trim((string)($in['type']??''));if(!in_array($type,['Municipal Activity','Alternative Activity'],true))jsonResponse(false,'Choose Municipal Activity or Alternative Activity.',422);$mode=strtolower(trim((string)($in['generateQr']??'')));if(!in_array($mode,['qr','proof','both'],true))jsonResponse(false,'Choose QR code, proof submission, or both.',422);$descriptionImage=array_key_exists('descriptionImage',$in)?trim((string)$in['descriptionImage']):(string)$oldImage;if(!empty($in['removeDescriptionImage']))$descriptionImage='';if($descriptionImage!==''&&array_key_exists('descriptionImage',$in)){if(strlen($descriptionImage)>3*1024*1024||!preg_match('#\Adata:image/(?:jpeg|png|webp);base64,([A-Za-z0-9+/]+={0,2})\z#',$descriptionImage,$imageMatch))jsonResponse(false,'Upload a JPG, PNG, or WebP image up to 2 MB.',422);$imageBytes=base64_decode($imageMatch[1],true);if($imageBytes===false||strlen($imageBytes)>2*1024*1024)jsonResponse(false,'Upload a JPG, PNG, or WebP image up to 2 MB.',422);}$s=$pdo->prepare('UPDATE activities SET name=?,type=?,activity_date=?,start_time=?,end_time=?,venue=?,venue_address=?,generate_qr=?,deadline_date=?,deadline_time=?,academic_year=?,semester=?,description=?,description_image=? WHERE id=?');$s->execute([$name,$type,$in['date']??'',$in['startTime']??'',$in['endTime']??'',$in['venue']??'',$in['venueAddress']??'',$mode,$in['deadlineDate']??'',$in['deadlineTime']??'',$in['academicYear']??'',$in['semester']??'',$in['description']??'',$descriptionImage,$id]);if(in_array($mode,['qr','both'],true)){$users=$pdo->query("SELECT id FROM users WHERE status='ACTIVE'")->fetchAll(PDO::FETCH_COLUMN);foreach($users as $participantId)activityQrToken($pdo,$id,(int)$participantId);}jsonResponse(true,'Activity updated.'); }
 if($action==='delete') { requireUser($pdo,['ADMIN','REPRESENTATIVE']); $id=(int)($in['id']??0);if(!$id)jsonResponse(false,'Invalid activity.',422);$s=$pdo->prepare('DELETE FROM activities WHERE id=?');$s->execute([$id]);if(!$s->rowCount())jsonResponse(false,'Activity not found.',404);jsonResponse(true,'Activity deleted.'); }
 if($action==='check-in') {
  requireUser($pdo,['ADMIN','REPRESENTATIVE']);
  $rawQr=trim((string)($in['qr_payload']??''));$scan=json_decode($rawQr,true);$expectedActivity=(int)($in['activity_id']??0);$legacy=is_array($scan)&&($scan['kind']??'')==='BASIS_ACTIVITY_ATTENDANCE';
  if($legacy){$activityId=(int)($scan['activity_id']??0);$userId=(int)($scan['user_id']??0);$token=(string)($scan['token']??'');}
  elseif(is_array($scan)&&isset($scan['activity_name'],$scan['name'],$scan['barangay'])&&$expectedActivity>0){$activityId=$expectedActivity;$s=$pdo->prepare('SELECT id,name,generate_qr FROM activities WHERE id=?');$s->execute([$activityId]);$activity=$s->fetch();if(!$activity)jsonResponse(false,'Activity not found.',404);if(!hash_equals((string)$activity['name'],(string)$scan['activity_name']))jsonResponse(false,'This QR code belongs to a different activity.',409);if(!in_array(strtolower((string)$activity['generate_qr']),['qr','both'],true))jsonResponse(false,'QR attendance is disabled for this activity.',403);$fullName="TRIM((CASE WHEN TRIM(given_name)<>'' THEN TRIM(given_name)||' ' ELSE '' END)||(CASE WHEN TRIM(middle_name)<>'' THEN TRIM(middle_name)||' ' ELSE '' END)||(CASE WHEN TRIM(surname)<>'' THEN TRIM(surname)||' ' ELSE '' END)||(CASE WHEN TRIM(suffix)<>'' THEN TRIM(suffix) ELSE '' END))";$findParticipant=$pdo->prepare("SELECT id,name,control_number,barangay FROM users WHERE status='ACTIVE' AND COALESCE(NULLIF($fullName,''),name)=? AND barangay=? ORDER BY id LIMIT 2");$findParticipant->execute([(string)$scan['name'],(string)$scan['barangay']]);$matches=$findParticipant->fetchAll();if(!$matches)jsonResponse(false,'Active participant not found.',404);if(count($matches)>1)jsonResponse(false,'More than one active user has this name and barangay. Update their profile details so the QR can identify them uniquely.',409);$participant=$matches[0];$userId=(int)$participant['id'];}
  elseif(preg_match('/^BASIS1:([a-f0-9]{48})$/',$rawQr,$tokenMatch)&&$expectedActivity>0){$activityId=$expectedActivity;$token=$tokenMatch[1];$tokenLookup=$pdo->prepare('SELECT user_id FROM activity_qr_tokens WHERE activity_id=? AND token=?');$tokenLookup->execute([$activityId,$token]);$userId=(int)($tokenLookup->fetchColumn()?:0);}
  else jsonResponse(false,'This is not a valid participant activity QR code.',422);
  if(!$activityId||!$userId)jsonResponse(false,'This activity QR code is invalid.',422);
  $s=$pdo->prepare('SELECT id,name,generate_qr FROM activities WHERE id=?');$s->execute([$activityId]);$activity=$s->fetch();
  if(!$activity)jsonResponse(false,'Activity not found.',404);
  if(!in_array(strtolower((string)$activity['generate_qr']),['qr','both'],true))jsonResponse(false,'QR attendance is disabled for this activity.',403);
  if(!isset($participant)){$s=$pdo->prepare("SELECT id,name,control_number,barangay FROM users WHERE id=? AND status='ACTIVE'");$s->execute([$userId]);$participant=$s->fetch();}
  if(!$participant)jsonResponse(false,'Active participant not found.',404);
  if(isset($token)){$tokenQuery=$pdo->prepare('SELECT token FROM activity_qr_tokens WHERE activity_id=? AND user_id=?');$tokenQuery->execute([$activityId,$userId]);$storedToken=$tokenQuery->fetchColumn();if($storedToken===false||!hash_equals((string)$storedToken,$token))jsonResponse(false,'This participant QR code is invalid or no longer active.',403);}
  if($legacy&&(!hash_equals((string)$activity['name'],(string)($scan['activity_name']??''))||!hash_equals((string)$participant['control_number'],(string)($scan['control_number']??''))||!hash_equals((string)$participant['name'],(string)($scan['name']??''))||!hash_equals((string)$participant['barangay'],(string)($scan['barangay']??''))))jsonResponse(false,'QR details do not match the participant or activity.',403);
  if($expectedActivity&&$expectedActivity!==$activityId)jsonResponse(false,'This QR code belongs to a different activity.',409);
  $s=$pdo->prepare("INSERT INTO activity_attendance(activity_id,user_id,attendance_date,time_in) VALUES(?,?,date('now','localtime'),time('now','localtime')) ON CONFLICT(activity_id,user_id) DO UPDATE SET time_out=CASE WHEN time_out='' THEN time('now','localtime') ELSE time_out END");$s->execute([$activityId,$userId]);
  $check=$pdo->prepare('SELECT time_in,time_out FROM activity_attendance WHERE activity_id=? AND user_id=?');$check->execute([$activityId,$userId]);
  jsonResponse(true,'Attendance recorded for '.(string)$participant['name'].' ('.(string)$participant['barangay'].').',200,['attendance'=>$check->fetch(),'participant'=>['name'=>$participant['name'],'barangay'=>$participant['barangay']]]);
 }
 if($action==='participants') { requireUser($pdo,['ADMIN','REPRESENTATIVE']);$activityId=(int)($_GET['activity_id']??0);$s=$pdo->prepare("SELECT u.name,u.control_number,u.barangay,x.attendance_date,COALESCE(x.time_in,'') AS time_in,COALESCE(x.time_out,'') AS time_out,CASE WHEN EXISTS(SELECT 1 FROM submissions s WHERE s.activity_id=? AND s.user_id=u.id AND s.status='VERIFIED') THEN 'Attended' WHEN EXISTS(SELECT 1 FROM submissions s WHERE s.activity_id=? AND s.user_id=u.id AND s.status='REJECTED') THEN 'Absent' WHEN UPPER(COALESCE(x.status,'')) IN ('PRESENT','ATTENDED') AND TRIM(COALESCE(x.time_in,''))<>'' THEN 'Attended' WHEN EXISTS(SELECT 1 FROM submissions s WHERE s.activity_id=? AND s.user_id=u.id AND s.status='PENDING') THEN 'Submitted' ELSE '—' END AS submission FROM users u LEFT JOIN activity_attendance x ON x.activity_id=? AND x.user_id=u.id WHERE UPPER(u.status)='ACTIVE' AND (x.user_id IS NOT NULL OR EXISTS(SELECT 1 FROM submissions s WHERE s.activity_id=? AND s.user_id=u.id AND s.file_data<>'')) ORDER BY COALESCE(x.time_in,''),u.name");$s->execute([$activityId,$activityId,$activityId,$activityId,$activityId]);jsonResponse(true,'',200,['participants'=>$s->fetchAll()]); }
 if($action==='submissions') { requireUser($pdo,['ADMIN','REPRESENTATIVE']);$activityId=(int)($_GET['activity_id']??0);$type=$_GET['type']??'';$sql='SELECT s.id,s.activity_id,s.user_id,u.name,u.email,u.barangay,s.submission_type,s.file_name,s.file_data,s.status,s.submitted_at FROM submissions s JOIN users u ON u.id=s.user_id WHERE s.activity_id=?';$values=[$activityId];if(in_array($type,['attendance','absence'],true)){$sql.=' AND s.submission_type=?';$values[]=$type;}if(($_GET['status']??'')==='pending')$sql.=" AND s.status='PENDING'";if(($_GET['status']??'')==='verified')$sql.=" AND s.status IN ('VERIFIED','REJECTED')";$sql.=' ORDER BY s.submitted_at DESC';$s=$pdo->prepare($sql);$s->execute($values);jsonResponse(true,'',200,['submissions'=>$s->fetchAll()]); }
 if($action==='verify') { requireUser($pdo,['ADMIN','REPRESENTATIVE']);$id=(int)($in['id']??0);$status=($in['status']??'')==='VERIFIED'?'VERIFIED':'REJECTED';$s=$pdo->prepare('SELECT activity_id,user_id FROM submissions WHERE id=?');$s->execute([$id]);$submission=$s->fetch();if(!$submission)jsonResponse(false,'Submission not found.',404);$pdo->beginTransaction();try{$u=$pdo->prepare('UPDATE submissions SET status=? WHERE id=?');$u->execute([$status,$id]);$attendanceStatus=$status==='VERIFIED'?'ATTENDED':'ABSENT';$att=$pdo->prepare("INSERT INTO activity_attendance(activity_id,user_id,attendance_date,time_in,time_out,status) VALUES(?,?,date('now','localtime'),'','',?) ON CONFLICT(activity_id,user_id) DO UPDATE SET status=excluded.status");$att->execute([(int)$submission['activity_id'],(int)$submission['user_id'],$attendanceStatus]);$pdo->commit();}catch(Throwable $e){$pdo->rollBack();throw $e;}jsonResponse(true,'Submission '.$status.'.'); }
 jsonResponse(false,'Unknown action.',400);
} catch(Throwable $e) { error_log($e->getMessage()); jsonResponse(false,'Server error.',500); }
