<?php
declare(strict_types=1);
require_once __DIR__ . '/db.php'; require_once __DIR__ . '/http.php';
try {
 $pdo=db(); $user=requireUser($pdo); $action=$_GET['action']??'list'; $in=requestInput();
 if($action==='list') { $s=$pdo->query("SELECT a.*, a.activity_date AS date, a.start_time AS startTime, a.end_time AS endTime, a.venue_address AS venueAddress, a.generate_qr AS generateQr, a.deadline_date AS deadlineDate, a.deadline_time AS deadlineTime, a.academic_year AS academicYear, COALESCE((SELECT COUNT(*) FROM activity_attendance x WHERE x.activity_id=a.id),0) AS participantCount FROM activities a ORDER BY a.activity_date DESC,a.id DESC"); jsonResponse(true,'',200,['activities'=>$s->fetchAll()]); }
 if($action==='create') { requireUser($pdo,['ADMIN','REPRESENTATIVE']); $name=trim((string)($in['name']??'')); if($name==='') jsonResponse(false,'Activity name is required.',422); $cols=['name','type','activity_date','start_time','end_time','venue','venue_address','generate_qr','deadline_date','deadline_time','academic_year','semester','description','municipality','barangay','created_by']; $vals=[$name,$in['type']??'',$in['date']??'',$in['startTime']??'',$in['endTime']??'',$in['venue']??'',$in['venueAddress']??'',$in['generateQr']??'',$in['deadlineDate']??'',$in['deadlineTime']??'',$in['academicYear']??'',$in['semester']??'',$in['description']??'',$in['municipality']??'',$in['barangay']??'',$user['id']];
  $s=$pdo->prepare('INSERT INTO activities('.implode(',',$cols).') VALUES('.implode(',',array_fill(0,count($cols),'?')).')'); $s->execute($vals); jsonResponse(true,'Activity created.',201,['id'=>(int)$pdo->lastInsertId()]); }
 if($action==='get') { $id=(int)($in['id']??$_GET['id']??0); if(!$id) jsonResponse(false,'Invalid activity.',422); $s=$pdo->prepare('SELECT *,activity_date AS date,start_time AS startTime,end_time AS endTime,venue_address AS venueAddress,generate_qr AS generateQr,deadline_date AS deadlineDate,deadline_time AS deadlineTime,academic_year AS academicYear FROM activities WHERE id=?');$s->execute([$id]);$a=$s->fetch();if(!$a)jsonResponse(false,'Activity not found.',404);jsonResponse(true,'',200,['activity'=>$a]); }
 if($action==='delete') { requireUser($pdo,['ADMIN','REPRESENTATIVE']); $id=(int)($in['id']??0);$s=$pdo->prepare('DELETE FROM activities WHERE id=?');$s->execute([$id]);if(!$s->rowCount())jsonResponse(false,'Activity not found.',404);jsonResponse(true,'Activity deleted.'); }
 if($action==='check-in') { requireUser($pdo,['ADMIN','REPRESENTATIVE']);$activityId=(int)($in['activity_id']??0);$userId=(int)($in['user_id']??0);if(!$activityId&& !empty($in['activity_token'])&&preg_match('/^BASIS-A:(\d+)$/',(string)$in['activity_token'],$m))$activityId=(int)$m[1];if(!$userId&& !empty($in['control_number'])){$u=$pdo->prepare('SELECT id FROM users WHERE control_number=? AND status=\'ACTIVE\'');$u->execute([trim((string)$in['control_number'])]);$userId=(int)$u->fetchColumn();}if(!$activityId||!$userId)jsonResponse(false,'A valid activity and user QR code are required.',422);$s=$pdo->prepare('SELECT generate_qr FROM activities WHERE id=?');$s->execute([$activityId]);$mode=$s->fetchColumn();if(!$mode)jsonResponse(false,'Activity not found.',404);if(!in_array(strtolower((string)$mode),['qr','both'],true))jsonResponse(false,'QR attendance is disabled for this activity.',403);$s=$pdo->prepare('SELECT id FROM users WHERE id=? AND status=\'ACTIVE\'');$s->execute([$userId]);if(!$s->fetchColumn())jsonResponse(false,'Active user not found.',404);$s=$pdo->prepare("INSERT INTO activity_attendance(activity_id,user_id,attendance_date,time_in) VALUES(?,?,date('now','localtime'),time('now','localtime')) ON CONFLICT(activity_id,user_id) DO UPDATE SET time_out=CASE WHEN time_out='' THEN time('now','localtime') ELSE time_out END");$s->execute([$activityId,$userId]);$check=$pdo->prepare('SELECT time_in,time_out FROM activity_attendance WHERE activity_id=? AND user_id=?');$check->execute([$activityId,$userId]);jsonResponse(true,'Attendance scan recorded.',200,['attendance'=>$check->fetch()]); }
 if($action==='participants') { requireUser($pdo,['ADMIN','REPRESENTATIVE']);$activityId=(int)($_GET['activity_id']??0);$s=$pdo->prepare('SELECT u.name,u.control_number,u.barangay,x.attendance_date,x.time_in,x.time_out,x.status FROM activity_attendance x JOIN users u ON u.id=x.user_id WHERE x.activity_id=? ORDER BY x.time_in');$s->execute([$activityId]);jsonResponse(true,'',200,['participants'=>$s->fetchAll()]); }
 if($action==='submissions') { requireUser($pdo,['ADMIN','REPRESENTATIVE']);$activityId=(int)($_GET['activity_id']??0);$type=$_GET['type']??'';$sql='SELECT s.id,s.activity_id,s.user_id,u.name,u.email,u.barangay,s.submission_type,s.file_name,s.file_data,s.status,s.submitted_at FROM submissions s JOIN users u ON u.id=s.user_id WHERE s.activity_id=?';$values=[$activityId];if(in_array($type,['attendance','absence'],true)){$sql.=' AND s.submission_type=?';$values[]=$type;}if(($_GET['status']??'')==='pending')$sql.=" AND s.status='PENDING'";if(($_GET['status']??'')==='verified')$sql.=" AND s.status IN ('VERIFIED','REJECTED')";$sql.=' ORDER BY s.submitted_at DESC';$s=$pdo->prepare($sql);$s->execute($values);jsonResponse(true,'',200,['submissions'=>$s->fetchAll()]); }
 if($action==='verify') { requireUser($pdo,['ADMIN','REPRESENTATIVE']);$id=(int)($in['id']??0);$status=($in['status']??'')==='VERIFIED'?'VERIFIED':'REJECTED';$s=$pdo->prepare('UPDATE submissions SET status=? WHERE id=?');$s->execute([$status,$id]);if(!$s->rowCount())jsonResponse(false,'Submission not found.',404);jsonResponse(true,'Submission '.$status.'.'); }
 jsonResponse(false,'Unknown action.',400);
} catch(Throwable $e) { error_log($e->getMessage()); jsonResponse(false,'Server error.',500); }
