<?php
declare(strict_types=1);
require_once __DIR__ . '/db.php'; require_once __DIR__ . '/http.php'; require_once __DIR__ . '/activity_qr_token.php';
try {
 $pdo=db(); $user=requireUser($pdo); $action=$_GET['action']??'list'; $in=requestInput();
 if($action==='list') { $s=$pdo->query("SELECT a.*, a.activity_date AS date, a.start_time AS startTime, a.end_time AS endTime, a.venue_address AS venueAddress, a.generate_qr AS generateQr, a.deadline_date AS deadlineDate, a.deadline_time AS deadlineTime, a.academic_year AS academicYear, COALESCE((SELECT COUNT(*) FROM activity_attendance x WHERE x.activity_id=a.id),0) AS participantCount FROM activities a ORDER BY a.activity_date DESC,a.id DESC"); jsonResponse(true,'',200,['activities'=>$s->fetchAll()]); }
 if($action==='create') { requireUser($pdo,['ADMIN','REPRESENTATIVE']); $name=trim((string)($in['name']??'')); if($name==='') jsonResponse(false,'Activity name is required.',422); $mode=strtolower(trim((string)($in['generateQr']??'')));if(!in_array($mode,['qr','proof','both'],true))jsonResponse(false,'Choose QR code, proof submission, or both.',422); $cols=['name','type','activity_date','start_time','end_time','venue','venue_address','generate_qr','deadline_date','deadline_time','academic_year','semester','description','municipality','barangay','created_by']; $vals=[$name,$in['type']??'',$in['date']??'',$in['startTime']??'',$in['endTime']??'',$in['venue']??'',$in['venueAddress']??'',$mode,$in['deadlineDate']??'',$in['deadlineTime']??'',$in['academicYear']??'',$in['semester']??'',$in['description']??'',$in['municipality']??'',$in['barangay']??'',$user['id']];
  $s=$pdo->prepare('INSERT INTO activities('.implode(',',$cols).') VALUES('.implode(',',array_fill(0,count($cols),'?')).')'); $s->execute($vals); $activityId=(int)$pdo->lastInsertId();if(in_array($mode,['qr','both'],true)){$users=$pdo->query("SELECT id FROM users WHERE status='ACTIVE'")->fetchAll(PDO::FETCH_COLUMN);foreach($users as $participantId)activityQrToken($pdo,$activityId,(int)$participantId);}jsonResponse(true,'Activity created and individual participant QR codes are ready.',201,['id'=>$activityId]); }
 if($action==='get') { $id=(int)($in['id']??$_GET['id']??0); if(!$id) jsonResponse(false,'Invalid activity.',422); $s=$pdo->prepare('SELECT *,activity_date AS date,start_time AS startTime,end_time AS endTime,venue_address AS venueAddress,generate_qr AS generateQr,deadline_date AS deadlineDate,deadline_time AS deadlineTime,academic_year AS academicYear FROM activities WHERE id=?');$s->execute([$id]);$a=$s->fetch();if(!$a)jsonResponse(false,'Activity not found.',404);jsonResponse(true,'',200,['activity'=>$a]); }
 if($action==='delete') { requireUser($pdo,['ADMIN','REPRESENTATIVE']); $id=(int)($in['id']??0);$s=$pdo->prepare('DELETE FROM activities WHERE id=?');$s->execute([$id]);if(!$s->rowCount())jsonResponse(false,'Activity not found.',404);jsonResponse(true,'Activity deleted.'); }
 if($action==='check-in') {
  requireUser($pdo,['ADMIN','REPRESENTATIVE']);
  $scan=json_decode((string)($in['qr_payload']??''),true);
  if(!is_array($scan)||($scan['kind']??'')!=='BASIS_ACTIVITY_ATTENDANCE')jsonResponse(false,'This is not a valid participant activity QR code.',422);
  $activityId=(int)($scan['activity_id']??0);$userId=(int)($scan['user_id']??0);$token=(string)($scan['token']??'');
  if(!$activityId||!$userId||!preg_match('/^[a-f0-9]{48}$/',$token))jsonResponse(false,'This activity QR code is incomplete or invalid.',422);
  $s=$pdo->prepare('SELECT id,name,generate_qr FROM activities WHERE id=?');$s->execute([$activityId]);$activity=$s->fetch();
  if(!$activity)jsonResponse(false,'Activity not found.',404);
  if(!in_array(strtolower((string)$activity['generate_qr']),['qr','both'],true))jsonResponse(false,'QR attendance is disabled for this activity.',403);
  $s=$pdo->prepare("SELECT id,name,control_number,barangay FROM users WHERE id=? AND status='ACTIVE'");$s->execute([$userId]);$participant=$s->fetch();
  if(!$participant)jsonResponse(false,'Active participant not found.',404);
  $tokenQuery=$pdo->prepare('SELECT token FROM activity_qr_tokens WHERE activity_id=? AND user_id=?');$tokenQuery->execute([$activityId,$userId]);$storedToken=$tokenQuery->fetchColumn();
  if($storedToken===false||!hash_equals((string)$storedToken,$token))jsonResponse(false,'This participant QR code is invalid or no longer active.',403);
  if(!hash_equals((string)$activity['name'],(string)($scan['activity_name']??''))||!hash_equals((string)$participant['control_number'],(string)($scan['control_number']??''))||!hash_equals((string)$participant['name'],(string)($scan['name']??''))||!hash_equals((string)$participant['barangay'],(string)($scan['barangay']??'')))jsonResponse(false,'QR details do not match the participant or activity.',403);
  $expectedActivity=(int)($in['activity_id']??0);if($expectedActivity&&$expectedActivity!==$activityId)jsonResponse(false,'This QR code belongs to a different activity.',409);
  $s=$pdo->prepare("INSERT INTO activity_attendance(activity_id,user_id,attendance_date,time_in) VALUES(?,?,date('now','localtime'),time('now','localtime')) ON CONFLICT(activity_id,user_id) DO UPDATE SET time_out=CASE WHEN time_out='' THEN time('now','localtime') ELSE time_out END");$s->execute([$activityId,$userId]);
  $check=$pdo->prepare('SELECT time_in,time_out FROM activity_attendance WHERE activity_id=? AND user_id=?');$check->execute([$activityId,$userId]);
  jsonResponse(true,'Attendance recorded for '.(string)$participant['name'].' ('.(string)$participant['barangay'].').',200,['attendance'=>$check->fetch(),'participant'=>['name'=>$participant['name'],'barangay'=>$participant['barangay']]]);
 }
 if($action==='participants') { requireUser($pdo,['ADMIN','REPRESENTATIVE']);$activityId=(int)($_GET['activity_id']??0);$s=$pdo->prepare('SELECT u.name,u.control_number,u.barangay,x.attendance_date,x.time_in,x.time_out,x.status FROM activity_attendance x JOIN users u ON u.id=x.user_id WHERE x.activity_id=? ORDER BY x.time_in');$s->execute([$activityId]);jsonResponse(true,'',200,['participants'=>$s->fetchAll()]); }
 if($action==='submissions') { requireUser($pdo,['ADMIN','REPRESENTATIVE']);$activityId=(int)($_GET['activity_id']??0);$type=$_GET['type']??'';$sql='SELECT s.id,s.activity_id,s.user_id,u.name,u.email,u.barangay,s.submission_type,s.file_name,s.file_data,s.status,s.submitted_at FROM submissions s JOIN users u ON u.id=s.user_id WHERE s.activity_id=?';$values=[$activityId];if(in_array($type,['attendance','absence'],true)){$sql.=' AND s.submission_type=?';$values[]=$type;}if(($_GET['status']??'')==='pending')$sql.=" AND s.status='PENDING'";if(($_GET['status']??'')==='verified')$sql.=" AND s.status IN ('VERIFIED','REJECTED')";$sql.=' ORDER BY s.submitted_at DESC';$s=$pdo->prepare($sql);$s->execute($values);jsonResponse(true,'',200,['submissions'=>$s->fetchAll()]); }
 if($action==='verify') { requireUser($pdo,['ADMIN','REPRESENTATIVE']);$id=(int)($in['id']??0);$status=($in['status']??'')==='VERIFIED'?'VERIFIED':'REJECTED';$s=$pdo->prepare('UPDATE submissions SET status=? WHERE id=?');$s->execute([$status,$id]);if(!$s->rowCount())jsonResponse(false,'Submission not found.',404);jsonResponse(true,'Submission '.$status.'.'); }
 jsonResponse(false,'Unknown action.',400);
} catch(Throwable $e) { error_log($e->getMessage()); jsonResponse(false,'Server error.',500); }
