/* BASIS REPRESENTATIVE — ACTIVITY DATA LOGIC
   No template/sample activity data.
   Activities appear only after the admin creates one. */

const ACTIVITY_STORAGE_KEY = 'basisRepresentativeActivities';
const SELECTED_ACTIVITY_KEY = 'basisRepresentativeSelectedActivityId';

async function activityRequest(action, body){ const r=await fetch(`../admin/api/activity_api.php?action=${action}`,{method:body?'POST':'GET',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}); const d=await r.json(); if(!r.ok||!d.success)throw new Error(d.message||'Activity request failed.'); return d; }
async function getActivities(){ return (await activityRequest('list')).activities||[]; }
async function getSelectedActivity(){ const id=sessionStorage.getItem(SELECTED_ACTIVITY_KEY); if(!id)return null; return (await activityRequest(`get&id=${encodeURIComponent(id)}`)).activity; }
function escapeHtml(v){ return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;'); }
function formatDate(v){ if(!v)return ''; const d=new Date(v+'T00:00:00'); return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-US',{month:'2-digit',day:'2-digit',year:'numeric'}); }
function setText(id,v){ const e=document.getElementById(id); if(e)e.textContent=v||''; }
function setAll(sel,v){ document.querySelectorAll(sel).forEach(e=>e.textContent=v||''); }
function semesterLabel(a){ return [a?.academicYear||'',a?.semester||''].filter(Boolean).join(' '); }

function fillActivityDetails(a){
 if(!a)return;
 const sem=semesterLabel(a), date=formatDate(a.date), time=[a.startTime,a.endTime].filter(Boolean).join(' - '), deadline=[formatDate(a.deadlineDate),a.deadlineTime].filter(Boolean).join(' ');
 setText('detailActivityTitle',a.name); setText('detailActivityType',a.type); setText('detailSemester',sem); setText('detailDate',date); setText('detailTime',time); setText('detailVenue',a.venue); setText('detailVenueAddress',a.venueAddress); setText('detailDescription',a.description); setText('detailDeadline',deadline);
 const descriptionImage=document.getElementById('detailDescriptionImage'); const imageSource=a.description_image||a.descriptionImage||''; if(descriptionImage){descriptionImage.hidden=!imageSource;if(imageSource)descriptionImage.src=imageSource;else descriptionImage.removeAttribute('src');}
 setText('qrSemester',sem); setText('qrTitle',a.name); setText('qrType',a.type); setText('qrDate',date); setText('qrTime',time); setText('qrVenue',a.venue); setText('qrVenueAddress',a.venueAddress); setText('qrName',a.name); setText('qrMunicipality',a.municipality); setText('qrBarangay',a.barangay); setText('qrDeadline',deadline);
 const qrImage=document.getElementById('activityQrImage'); if(qrImage){const enabled=['qr','both'].includes(String(a.generateQr||a.generate_qr||'').toLowerCase());qrImage.hidden=!enabled;if(enabled)qrImage.src=`../admin/api/activity_qr.php?id=${encodeURIComponent(a.id)}`;}
 loadQrUserOptions(a);
 setText('submissionSemester',sem); setText('submissionDate',date); setText('submissionTime',a.deadlineTime); setText('submissionTitle',a.name); setText('submissionType',a.type); setText('submissionInfoDate',date); setText('submissionInfoTime',time); setText('submissionVenue',a.venue); setText('submissionVenueAddress',a.venueAddress); setText('submissionName',a.name); setText('submissionMunicipality',a.municipality); setText('submissionBarangay',a.barangay);
 setText('menuActivityTitle',a.name); setText('participantsActivityTitle',a.name); setText('scanActivityTitle',a.name); setText('scanSemester',sem); setText('scanDate',date); setText('scanTime',time); setText('scanVenue',a.venue); setText('scanVenueAddress',a.venueAddress); setText('scanDeadline',deadline); setText('scanDescription',a.description);
 const canQr=['qr','both'].includes(String(a.generateQr||a.generate_qr||'').toLowerCase());document.querySelectorAll('[data-requires-qr]').forEach(el=>el.hidden=!canQr);document.querySelectorAll('[data-requires-proof]').forEach(el=>el.hidden=!['proof','both'].includes(String(a.generateQr||a.generate_qr||'').toLowerCase()));
 setAll('.verify-title',a.name); setAll('.verify-sem',sem); setAll('.verify-date',date); setAll('.verify-time',time); setAll('.verify-venue',a.venue); setAll('.verify-address',a.venueAddress); setAll('.verify-name',a.name); setAll('.verify-municipality',a.municipality); setAll('.verify-barangay',a.barangay); setAll('.verify-deadline',deadline);
}

async function loadQrUserOptions(activity){const select=document.getElementById('activityQrUserSelect');if(!select)return;select.innerHTML='<option value="">Loading scholars…</option>';try{const data=await activityRequest(`qr-users&activity_id=${encodeURIComponent(activity.id)}`);const users=data.users||[];select.innerHTML='<option value="">Select an iskolar</option>';users.forEach(user=>{const option=document.createElement('option');option.value=String(user.id);option.textContent=`${user.name} — ${user.barangay||'No barangay'}`;option.dataset.name=user.name||'';option.dataset.barangay=user.barangay||'';select.appendChild(option);});select.onchange=()=>{const option=select.selectedOptions[0],image=document.getElementById('activityQrImage');if(image){image.hidden=!select.value;if(select.value)image.src=`../admin/api/activity_qr.php?id=${encodeURIComponent(activity.id)}&user_id=${encodeURIComponent(select.value)}`;}setText('qrName',option?.dataset.name||'');setText('qrBarangay',option?.dataset.barangay||'');};select.dispatchEvent(new Event('change'));if(!users.length)select.innerHTML='<option value="">No active iskolar found</option>';}catch(error){select.innerHTML='<option value="">Could not load iskolar list</option>';console.warn(error.message);}}

async function renderActivityList(){
 const list=document.getElementById('adminActivityList'); if(!list)return; let items=[]; try{items=await getActivities();}catch(e){list.textContent=e.message;return;} list.innerHTML='';
 if(!items.length){ list.innerHTML='<div class="admin-no-activity"><i class="fa-solid fa-book-open"></i><h3>No activities yet.</h3><p>Created activities will appear here.</p></div>'; return; }
 items.forEach(a=>{ const card=document.createElement('div'); card.className='admin-activity-card'; card.innerHTML=`<div><h3>${escapeHtml(a.name)}</h3><span>${escapeHtml(formatDate(a.date||a.activity_date))}</span></div><button class="open-activity-btn" type="button">OPEN</button>`; card.querySelector('button').onclick=()=>{sessionStorage.setItem(SELECTED_ACTIVITY_KEY,String(a.id));window.location.href='activity_menu-rep.html';}; list.appendChild(card); });
}

function bindActivityImagePreview(){ const input=document.getElementById('activityDescriptionImage'),preview=document.getElementById('activityImagePreview'); if(!input||!preview)return; input.addEventListener('change',()=>{const file=input.files?.[0];if(!file){preview.hidden=true;preview.removeAttribute('src');return;}if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>2*1024*1024){alert('Choose a JPG, PNG, or WebP image up to 2 MB.');input.value='';preview.hidden=true;preview.removeAttribute('src');return;}preview.src=URL.createObjectURL(file);preview.hidden=false;}); }
function readActivityDescriptionImage(){ const input=document.getElementById('activityDescriptionImage'),file=input?.files?.[0];if(!file)return Promise.resolve('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>2*1024*1024)return Promise.reject(new Error('Choose a JPG, PNG, or WebP image up to 2 MB.'));return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(new Error('Could not read the selected image.'));reader.readAsDataURL(file);}); }
function setupCreateActivity(){
 const btn=document.querySelector('.create-btn'); if(!btn)return; bindActivityImagePreview(); btn.onclick=async function(e){ e.preventDefault(); const name=document.getElementById('activityName')?.value.trim()||''; if(!name){alert('Please enter an activity name.');return;} try{const descriptionImage=await readActivityDescriptionImage();const a={name,type:document.getElementById('activityType')?.value||'',date:document.getElementById('activityDate')?.value||'',startTime:document.getElementById('activityStartTime')?.value||'',endTime:document.getElementById('activityEndTime')?.value||'',venue:document.getElementById('activityVenue')?.value.trim()||'',venueAddress:document.getElementById('activityVenueAddress')?.value.trim()||'',generateQr:document.getElementById('generateQr')?.value||'',deadlineDate:document.getElementById('activityDeadlineDate')?.value||'',deadlineTime:document.getElementById('activityDeadlineTime')?.value||'',academicYear:document.getElementById('academicYear')?.value.trim()||'',semester:document.getElementById('semester')?.value||'',description:document.getElementById('activityDescription')?.value.trim()||'',descriptionImage,municipality:'',barangay:''};const d=await activityRequest('create',a);sessionStorage.setItem(SELECTED_ACTIVITY_KEY,String(d.id));window.location.href='activity-rep.html';}catch(err){alert(err.message);} };
}
let activityParticipantRows=[];
async function loadActivityParticipants(){const id=sessionStorage.getItem(SELECTED_ACTIVITY_KEY);if(!id)return;try{const data=await activityRequest(`participants&activity_id=${encodeURIComponent(id)}`);activityParticipantRows=data.participants||[];const body=document.getElementById('participantsTableBody');if(!body)return;body.innerHTML=activityParticipantRows.length?'':'<tr><td colspan="5" class="empty-table-cell">No participants yet.</td></tr>';activityParticipantRows.forEach(row=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${escapeHtml(row.name)}</td><td>${escapeHtml(row.barangay||'—')}</td><td>${escapeHtml(row.time_in||'—')}</td><td>${escapeHtml(row.time_out||'—')}</td><td>${escapeHtml(row.status||'PRESENT')}</td>`;body.appendChild(tr);});}catch(error){console.warn(error.message);}}
window.exportActivityParticipants=function(){if(!activityParticipantRows.length){alert('There are no attendance records to export yet.');return;}if(!window.XLSX){alert('Excel export could not load. Refresh the page and try again.');return;}const rows=activityParticipantRows.map(row=>({'CONTROL NUMBER':row.control_number||'','NAME':row.name||'','BARANGAY':row.barangay||'','ATTENDANCE DATE':row.attendance_date||'','TIME IN':row.time_in||'','TIME OUT':row.time_out||'','STATUS':row.status||'PRESENT'}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Attendance');const title=(document.getElementById('participantsActivityTitle')?.textContent||'activity').replace(/[^a-z0-9-_]+/gi,'_');XLSX.writeFile(wb,`BASIS_${title}_attendance.xlsx`);};

window.setSubmissionTab=function(t){const a=document.getElementById('tabAttendance'),b=document.getElementById('tabAbsence');if(!a||!b)return;a.classList.toggle('active',t==='attendance');b.classList.toggle('active',t==='absence');};
let activeScannerStream=null; let activeHtml5Scanner=null;
window.runScan=async function(){
 const button=document.getElementById('scanActionBtn'),mount=document.getElementById('qrScannerMount'),video=document.getElementById('qrScanVideo'),status=document.getElementById('scanStatus');
 if(!button)return;
 const activity=await getSelectedActivity();
 if(!activity){alert('Open an activity first.');return;}
 const setStatus=(message)=>{if(status)status.textContent=message;};
 const stop=async()=>{if(activeHtml5Scanner){try{await activeHtml5Scanner.stop();await activeHtml5Scanner.clear();}catch{}activeHtml5Scanner=null;}if(activeScannerStream){activeScannerStream.getTracks().forEach(track=>track.stop());activeScannerStream=null;}if(mount)mount.hidden=true;if(video)video.hidden=true;button.disabled=false;button.textContent='SCAN';};window.stopActivityScanner=stop;
 const record=async(value)=>{let payload;try{payload=JSON.parse(value);}catch{payload=null;}const newFormat=payload&&payload.activity_name&&payload.name&&Object.prototype.hasOwnProperty.call(payload,'barangay');const oldFormat=payload?.kind==='BASIS_ACTIVITY_ATTENDANCE';const tokenFormat=/^BASIS1:[a-f0-9]{48}$/.test(value);if(!newFormat&&!oldFormat&&!tokenFormat)throw new Error('This is not a participant activity QR code.');if(oldFormat&&Number(payload.activity_id)!==Number(activity.id))throw new Error('This QR code belongs to a different activity.');if(newFormat&&String(payload.activity_name)!==String(activity.name))throw new Error('This QR code belongs to a different activity.');const result=await activityRequest('check-in',{activity_id:Number(activity.id),qr_payload:value});setStatus(result.message);await stop();};
 if(window.Html5Qrcode){
  if(!navigator.mediaDevices?.getUserMedia){setStatus('Camera access is unavailable in this browser. Open this site on localhost and allow camera permission.');return;}
  try{button.disabled=true;button.textContent='SCANNING...';mount.hidden=false;setStatus('Allow camera access, then hold the iskolar QR inside the scan frame.');activeHtml5Scanner=new Html5Qrcode('qrScannerMount',{formatsToSupport:[Html5QrcodeSupportedFormats.QR_CODE]});await activeHtml5Scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:250,height:250}},async(decoded)=>{if(button.disabled&&activeHtml5Scanner){try{await record(decoded);}catch(error){setStatus(error.message);await stop();}}},()=>{});return;}catch(error){await stop();setStatus('Could not start the camera scanner: '+error.message+' Check browser camera permission and reload.');return;}
 }
 if(!('BarcodeDetector'in window)||!navigator.mediaDevices?.getUserMedia){setStatus('The QR scanner could not load. Check your internet connection and allow camera permission, then reload.');return;}
 try{activeScannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});video.srcObject=activeScannerStream;video.hidden=false;mount.hidden=true;await video.play();button.disabled=true;button.textContent='SCANNING...';setStatus('Hold the iskolar QR inside the camera view.');const detector=new BarcodeDetector({formats:['qr_code']});const scan=async()=>{if(!activeScannerStream)return;try{const codes=await detector.detect(video);if(codes.length){try{await record(codes[0].rawValue||'');}catch(error){setStatus(error.message);stop();}}else requestAnimationFrame(scan);}catch(error){setStatus(error.message);stop();}};requestAnimationFrame(scan);}catch(error){setStatus('Camera unavailable: '+error.message);await stop();}
};
window.openVerifyDetail=function(t){showSubView(t==='attendance'?'view-activity-verify-attendance':'view-activity-verify-absence');};
window.resolveVerification=function(){showSubView('view-activity-verify');};
window.submitNewActivity=function(){document.querySelector('.create-btn')?.click();};

document.addEventListener('DOMContentLoaded',async()=>{ if(document.getElementById('adminActivityList'))renderActivityList(); if(document.getElementById('activityName'))setupCreateActivity(); if(document.getElementById('scanActionBtn'))document.addEventListener('visibilitychange',()=>{if(document.hidden)window.stopActivityScanner?.();}); try{const a=await getSelectedActivity();if(a)fillActivityDetails(a);if(document.getElementById('participantsTableBody'))await loadActivityParticipants();}catch(e){console.warn(e.message);} });
