document.addEventListener('DOMContentLoaded',async()=>{
    const list=document.getElementById('repReportActivityFilters'),years=document.getElementById('repReportYearFilters'),results=document.getElementById('repReportResults'),count=document.getElementById('repReportResultCount');
    if(!list||!results)return;
    const api='../admin/api/activity_api.php';let activities=[],generated=[];
    const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const request=async action=>{const response=await fetch(`${api}?action=${action}`,{credentials:'same-origin',cache:'no-store'});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'Could not load report data.');return data;};
    try{
        activities=(await request('list')).activities||[];list.replaceChildren();
        if(!activities.length)list.textContent='No activities available.';
        activities.forEach(activity=>{const label=document.createElement('label');label.className='report-checkbox';const box=document.createElement('input');box.type='checkbox';box.value=String(activity.id);box.className='rep-report-activity';const text=document.createElement('span');text.textContent=activity.name||activity.title||'Activity';label.append(box,text);list.appendChild(label);});
        const yearValues=[...new Set(activities.map(a=>String(a.academicYear||a.academic_year||'').trim()).filter(Boolean))].sort();years.replaceChildren();if(!yearValues.length)years.textContent='No academic years available.';yearValues.forEach(year=>{const label=document.createElement('label');label.className='report-checkbox';const box=document.createElement('input');box.type='checkbox';box.value=year;box.className='rep-report-year';const text=document.createElement('span');text.textContent=year;label.append(box,text);years.appendChild(label);});
    }catch(error){list.textContent=error.message;}
    document.getElementById('repGenerateReport')?.addEventListener('click',async()=>{
        const selected=[...document.querySelectorAll('.rep-report-activity:checked')].map(el=>el.value);if(!selected.length){alert('Select at least one activity.');return;}
        const semesters=[...document.querySelectorAll('.rep-report-semester:checked')].map(el=>el.value.toLowerCase());const selectedYears=[...document.querySelectorAll('.rep-report-year:checked')].map(el=>el.value);results.textContent='Loading report…';generated=[];
        try{for(const id of selected){const activity=activities.find(a=>String(a.id)===id);if(!activity)continue;const sem=String(activity.semester||'').toLowerCase();const year=String(activity.academicYear||activity.academic_year||'');if(semesters.length&&!semesters.some(item=>sem.includes(item.replace(' semester',''))))continue;if(selectedYears.length&&!selectedYears.includes(year))continue;const response=await fetch(`${api}?action=participants&activity_id=${encodeURIComponent(id)}`,{credentials:'same-origin',cache:'no-store'});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'Could not load participants.');(data.participants||[]).forEach(person=>generated.push({activity:activity.name||activity.title||'',controlNumber:person.control_number||'',name:person.name||'',barangay:person.barangay||'',timeIn:person.time_in||'',timeOut:person.time_out||'',status:person.submission||'—'}));}
            results.replaceChildren();if(!generated.length){results.innerHTML='<div class="report-empty-state"><h3>No participant records match the selected filters.</h3></div>';count.textContent='0 records';return;}
            const table=document.createElement('table');table.className='report-table';table.innerHTML='<thead><tr><th>ACTIVITY</th><th>CONTROL NO.</th><th>NAME</th><th>BARANGAY</th><th>TIME IN</th><th>TIME OUT</th><th>STATUS</th></tr></thead>';const body=document.createElement('tbody');generated.forEach(row=>{const tr=document.createElement('tr');[row.activity,row.controlNumber,row.name,row.barangay,row.timeIn,row.timeOut,row.status].forEach(value=>{const td=document.createElement('td');td.textContent=value;tr.appendChild(td);});body.appendChild(tr);});table.appendChild(body);const wrap=document.createElement('div');wrap.className='report-table-wrap';wrap.appendChild(table);results.appendChild(wrap);count.textContent=`${generated.length} records`;
        }catch(error){results.textContent=error.message;count.textContent='0 records';}
    });
    document.getElementById('repClearReport')?.addEventListener('click',()=>{document.querySelectorAll('.rep-report-activity,.rep-report-year,.rep-report-semester').forEach(el=>el.checked=false);generated=[];results.innerHTML='<div class="report-empty-state"><h3>No report generated yet.</h3><p>Select the filters and click GENERATE.</p></div>';count.textContent='0 records';});
    document.getElementById('repExportReport')?.addEventListener('click',()=>{if(!generated.length){alert('Generate a report first.');return;}if(!window.XLSX){alert('Excel export could not load.');return;}const rows=generated.map(row=>({'ACTIVITY':row.activity,'CONTROL NO.':row.controlNumber,'NAME':row.name,'BARANGAY':row.barangay,'TIME IN':row.timeIn,'TIME OUT':row.timeOut,'STATUS':row.status}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Report');XLSX.writeFile(wb,'BASIS_Representative_Activity_Report.xlsx');});
});
