/* BASIS ADMIN — ACTIVITY DATA LOGIC
   No template/sample activity data.
   Activities appear only after the admin creates one. */

const ACTIVITY_STORAGE_KEY = 'basisAdminActivities';
const SELECTED_ACTIVITY_KEY = 'basisAdminSelectedActivityId';
let pendingSubmissions = [];
let currentSubmission = null;

async function activityRequest(action, body){ const r=await fetch(`api/activity_api.php?action=${action}`,{method:body?'POST':'GET',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}); const d=await r.json(); if(!r.ok||!d.success)throw new Error(d.message||'Activity request failed.'); return d; }
async function getActivities(){ return (await activityRequest('list')).activities||[]; }
async function getSelectedActivity(){ const id=sessionStorage.getItem(SELECTED_ACTIVITY_KEY); if(!id)return null; return (await activityRequest(`get&id=${encodeURIComponent(id)}`)).activity; }
function escapeHtml(v){ return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;'); }
function formatDate(v){ if(!v)return ''; const d=new Date(v+'T00:00:00'); return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-US',{month:'2-digit',day:'2-digit',year:'numeric'}); }
function setText(id,v){ const e=document.getElementById(id); if(e)e.textContent=v||''; }
function setAll(sel,v){ document.querySelectorAll(sel).forEach(e=>e.textContent=v||''); }
function semesterLabel(a){ return [a?.academicYear||'',a?.semester||''].filter(Boolean).join(' '); }
async function loadPersonalActivityQr(image, activityId){
 if(!image)return;
 try{const response=await fetch(`api/activity_qr.php?id=${encodeURIComponent(activityId)}`,{credentials:'same-origin',cache:'no-store'});if(!response.ok)throw new Error('QR could not be loaded.');const blob=await response.blob();if(image.dataset.qrObjectUrl)URL.revokeObjectURL(image.dataset.qrObjectUrl);image.dataset.qrObjectUrl=URL.createObjectURL(blob);image.src=image.dataset.qrObjectUrl;}catch(error){image.removeAttribute('src');console.error(error.message);}
}
window.downloadPersonalActivityQr=function(){const image=document.getElementById('activityQrImage');if(!image?.dataset.qrObjectUrl)return;const link=document.createElement('a');link.href=image.dataset.qrObjectUrl;link.download='BASIS-activity-attendance-QR.svg';link.click();};
async function fillPersonalActivityQrDetails(a,date,time,deadline,sem){[['activityQrSemester',sem],['activityQrTitle',a.name],['activityQrType',a.type],['activityQrDate',date],['activityQrTime',time],['activityQrVenue',a.venue],['activityQrVenueAddress',a.venueAddress],['activityQrMunicipality',a.municipality],['activityQrBarangay',a.barangay],['activityQrDeadline',deadline]].forEach(([id,value])=>setText(id,value));try{const response=await fetch('api/account_api.php?action=profile',{credentials:'same-origin',cache:'no-store'});const data=await response.json();if(response.ok&&data.success){const p=data.profile||{};const fullName=[p.givenName,p.middleName,p.surname,p.suffix].map(value=>String(value||'').trim()).filter(Boolean).join(' ');setText('activityQrParticipant',fullName||p.name||'—');setText('activityQrParticipantBarangay',p.barangay||'—');}}catch(error){console.error('Unable to load QR profile details:',error.message);}}

function fillActivityDetails(a){
 if(!a)return;
 const sem=semesterLabel(a), date=formatDate(a.date), time=[a.startTime,a.endTime].filter(Boolean).join(' - '), deadline=[formatDate(a.deadlineDate),a.deadlineTime].filter(Boolean).join(' ');
 setText('detailActivityTitle',a.name); setText('detailActivityType',a.type); setText('detailSemester',sem); setText('detailDate',date); setText('detailTime',time); setText('detailVenue',a.venue); setText('detailVenueAddress',a.venueAddress); setText('detailDescription',a.description); setText('detailDeadline',deadline);
 const descriptionImage=document.getElementById('detailDescriptionImage'); const imageSource=a.description_image||a.descriptionImage||''; if(descriptionImage){descriptionImage.hidden=!imageSource;if(imageSource)descriptionImage.src=imageSource;else descriptionImage.removeAttribute('src');}
 setText('qrSemester',sem); setText('qrTitle',a.name); setText('qrType',a.type); setText('qrDate',date); setText('qrTime',time); setText('qrVenue',a.venue); setText('qrVenueAddress',a.venueAddress); setText('qrName',a.name); setText('qrMunicipality',a.municipality); setText('qrBarangay',a.barangay); setText('qrDeadline',deadline);
 const qrImage=document.getElementById('activityQrImage'); if(qrImage){const enabled=['qr','both'].includes(String(a.generateQr||a.generate_qr||'').toLowerCase());qrImage.hidden=!enabled;if(enabled)loadPersonalActivityQr(qrImage,a.id);}
 fillPersonalActivityQrDetails(a,date,time,deadline,sem);
 setText('submissionSemester',sem); setText('submissionDeadline',formatDate(a.deadlineDate)); setText('submissionDate',date); setText('submissionTime',a.deadlineTime); setText('submissionTitle',a.name); setText('submissionType',a.type); setText('submissionActivityTime',time); setText('submissionInfoDate',date); setText('submissionInfoTime',time); setText('submissionVenue',a.venue); setText('submissionVenueAddress',a.venueAddress); setText('submissionName',a.name); setText('submissionMunicipality',a.municipality); setText('submissionBarangay',a.barangay);
 setText('menuActivityTitle',a.name); setText('participantsActivityTitle',a.name); setText('scanActivityTitle',a.name); setText('scanSemester',sem); setText('scanDate',date); setText('scanTime',time); setText('scanVenue',a.venue); setText('scanVenueAddress',a.venueAddress); setText('scanDeadline',deadline); setText('scanDescription',a.description);
 const canQr=['qr','both'].includes(String(a.generateQr||a.generate_qr||'').toLowerCase());document.querySelectorAll('[data-requires-qr]').forEach(el=>el.hidden=!canQr);document.querySelectorAll('[data-requires-proof]').forEach(el=>el.hidden=!['proof','both'].includes(String(a.generateQr||a.generate_qr||'').toLowerCase()));
 setAll('.verify-title',a.name); setAll('.verify-sem',sem); setAll('.verify-date',date); setAll('.verify-time',time); setAll('.verify-venue',a.venue); setAll('.verify-address',a.venueAddress); setAll('.verify-name',a.name); setAll('.verify-municipality',a.municipality); setAll('.verify-barangay',a.barangay); setAll('.verify-deadline',deadline);
}


async function renderActivityList(){
 const list=document.getElementById('adminActivityList'); if(!list)return; let items=[]; try{items=await getActivities();}catch(e){list.textContent=e.message;return;} list.innerHTML='';
 if(!items.length){ list.innerHTML='<div class="admin-no-activity"><i class="fa-solid fa-book-open"></i><h3>No activities yet.</h3><p>Created activities will appear here.</p></div>'; return; }
 items.forEach(a=>{ const card=document.createElement('div'); card.className='admin-activity-card'; card.innerHTML=`<div><h3>${escapeHtml(a.name)}</h3><span>${escapeHtml(formatDate(a.date||a.activity_date))}</span></div><button class="open-activity-btn" type="button">OPEN</button>`; card.querySelector('button').onclick=()=>{sessionStorage.setItem(SELECTED_ACTIVITY_KEY,String(a.id));window.location.href='activity_menu-admin.html';}; list.appendChild(card); });
}

function bindActivityImagePreview(){ const input=document.getElementById('activityDescriptionImage'),preview=document.getElementById('activityImagePreview'); if(!input||!preview)return; input.addEventListener('change',()=>{const file=input.files?.[0];if(!file){preview.hidden=true;preview.removeAttribute('src');return;}if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>2*1024*1024){alert('Choose a JPG, PNG, or WebP image up to 2 MB.');input.value='';preview.hidden=true;preview.removeAttribute('src');return;}preview.src=URL.createObjectURL(file);preview.hidden=false;}); }
function readActivityDescriptionImage(){ const input=document.getElementById('activityDescriptionImage'),file=input?.files?.[0];if(!file)return Promise.resolve('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>2*1024*1024)return Promise.reject(new Error('Choose a JPG, PNG, or WebP image up to 2 MB.'));return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(new Error('Could not read the selected image.'));reader.readAsDataURL(file);}); }
window.editSelectedActivity=function(){const id=sessionStorage.getItem(SELECTED_ACTIVITY_KEY);if(!id){alert('Open an activity first.');return;}sessionStorage.setItem('basisActivityEditMode','1');window.location.href='activity_create-admin.html';};
window.deleteSelectedActivity=async function(){const id=sessionStorage.getItem(SELECTED_ACTIVITY_KEY);if(!id){alert('Open an activity first.');return;}if(!confirm('Are you sure you want to delete this activity? Its attendance and submissions will also be deleted. This cannot be undone.'))return;try{await activityRequest('delete',{id:Number(id)});sessionStorage.removeItem(SELECTED_ACTIVITY_KEY);sessionStorage.removeItem('basisActivityEditMode');alert('Activity deleted.');window.location.href='activity-admin.html';}catch(error){alert(error.message);}};
function setActivityFormFromRecord(a){const values={activityName:a.name,activityType:a.type,activityDate:a.date||a.activity_date,activityStartTime:a.startTime||a.start_time,activityEndTime:a.endTime||a.end_time,activityVenue:a.venue,activityVenueAddress:a.venueAddress||a.venue_address,generateQr:a.generateQr||a.generate_qr,activityDeadlineDate:a.deadlineDate||a.deadline_date,activityDeadlineTime:a.deadlineTime||a.deadline_time,academicYear:a.academicYear||a.academic_year,semester:a.semester,activityDescription:a.description};Object.entries(values).forEach(([id,value])=>{const field=document.getElementById(id);if(field)field.value=value||'';});const image=a.description_image||'';const preview=document.getElementById('activityImagePreview');if(preview&&image){preview.src=image;preview.hidden=false;}}
function setupCreateActivity(){
 const btn=document.querySelector('.create-btn');if(!btn)return;bindActivityImagePreview();const editing=sessionStorage.getItem('basisActivityEditMode')==='1';const title=document.getElementById('activityFormTitle'),back=document.getElementById('activityFormBack');if(editing){btn.disabled=true;btn.textContent='SAVE CHANGES';if(title)title.textContent='EDIT ACTIVITY';if(back)back.onclick=()=>{sessionStorage.removeItem('basisActivityEditMode');window.location.href='activity_menu-admin.html';};getSelectedActivity().then(a=>{if(a)setActivityFormFromRecord(a);else{alert('Activity not found.');window.location.href='activity-admin.html';}}).catch(error=>alert(error.message)).finally(()=>btn.disabled=false);}
 btn.onclick=async function(e){e.preventDefault();const name=document.getElementById('activityName')?.value.trim()||'';if(!name){alert('Please enter an activity name.');return;}try{const descriptionImage=await readActivityDescriptionImage();const a={name,type:document.getElementById('activityType')?.value||'',date:document.getElementById('activityDate')?.value||'',startTime:document.getElementById('activityStartTime')?.value||'',endTime:document.getElementById('activityEndTime')?.value||'',venue:document.getElementById('activityVenue')?.value.trim()||'',venueAddress:document.getElementById('activityVenueAddress')?.value.trim()||'',generateQr:document.getElementById('generateQr')?.value||'',deadlineDate:document.getElementById('activityDeadlineDate')?.value||'',deadlineTime:document.getElementById('activityDeadlineTime')?.value||'',academicYear:document.getElementById('academicYear')?.value.trim()||'',semester:document.getElementById('semester')?.value||'',description:document.getElementById('activityDescription')?.value.trim()||'',municipality:'',barangay:''};if(descriptionImage)a.descriptionImage=descriptionImage;if(editing){a.id=Number(sessionStorage.getItem(SELECTED_ACTIVITY_KEY));await activityRequest('update',a);sessionStorage.removeItem('basisActivityEditMode');alert('Activity updated.');window.location.href='activity_menu-admin.html';}else{const result=await activityRequest('create',a);sessionStorage.setItem(SELECTED_ACTIVITY_KEY,String(result.id));window.location.href='activity-admin.html';}}catch(error){alert(error.message);}};
}

window.setSubmissionTab=function(t){const a=document.getElementById('tabAttendance'),b=document.getElementById('tabAbsence');if(!a||!b)return;a.classList.toggle('active',t==='attendance');b.classList.toggle('active',t==='absence');};
let activeScannerStream=null; let activeHtml5Scanner=null;
async function submitScannedActivityQr(value, activity){let payload;let qrPayload=value;try{payload=JSON.parse(value);}catch{payload=null;}if(!payload){const parts=String(value).split(/\r?\n/).map(part=>part.trim()).filter(Boolean);if(parts.length===3){payload={activity_name:parts[0],name:parts[1],barangay:parts[2]};qrPayload=JSON.stringify(payload);}}const newFormat=payload&&payload.activity_name&&payload.name&&Object.prototype.hasOwnProperty.call(payload,'barangay');const oldFormat=payload?.kind==='BASIS_ACTIVITY_ATTENDANCE';const tokenFormat=/^BASIS1:[a-f0-9]{48}$/.test(value);if(!newFormat&&!oldFormat&&!tokenFormat)throw new Error('This is not a valid BASIS activity QR.');if(oldFormat&&Number(payload.activity_id)!==Number(activity.id))throw new Error('This QR belongs to a different activity.');if(newFormat&&String(payload.activity_name)!==String(activity.name))throw new Error('This QR belongs to a different activity.');return activityRequest('check-in',{activity_id:Number(activity.id),qr_payload:qrPayload});}
async function prepareQrImageVariants(file){const variants=[file];if(!('createImageBitmap'in window))return variants;let bitmap;try{bitmap=await createImageBitmap(file);for(const scale of [2,3]){const canvas=document.createElement('canvas');const maxSide=1800;const factor=Math.min(scale,maxSide/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*factor));canvas.height=Math.max(1,Math.round(bitmap.height*factor));const context=canvas.getContext('2d');context.filter='grayscale(1) contrast(1.35)';context.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(blob)variants.push(blob);}}catch{}finally{bitmap?.close();}return variants;}
window.importActivityQr=async function(){const input=document.getElementById('qrImportFile'),mount=document.getElementById('qrScannerMount'),status=document.getElementById('scanStatus'),file=input?.files?.[0];if(!file)return;try{const activity=await getSelectedActivity();if(!activity)throw new Error('Open an activity first.');if(status)status.textContent='Reading QR image…';const variants=await prepareQrImageVariants(file);let decoded='';for(const image of variants){if(window.Html5Qrcode){let decoder;try{mount.hidden=false;decoder=new Html5Qrcode('qrScannerMount',{formatsToSupport:[Html5QrcodeSupportedFormats.QR_CODE]});decoded=await decoder.scanFile(image,false);if(decoded)break;}catch{}finally{if(decoder){try{await decoder.clear();}catch{}}mount.hidden=true;}}if(!decoded&&'BarcodeDetector'in window){let bitmap;try{bitmap=await createImageBitmap(image);const codes=await new BarcodeDetector({formats:['qr_code']}).detect(bitmap);if(codes.length){decoded=codes[0].rawValue||'';if(decoded)break;}}catch{}finally{bitmap?.close();}}}if(!decoded)throw new Error('Could not read a QR code from this image. Try a sharper, uncropped QR image with the whole code visible.');const result=await submitScannedActivityQr(decoded,activity);if(status)status.textContent=result.message;}catch(error){if(status)status.textContent=error.message||'Could not read that QR image.';}finally{if(mount)mount.hidden=true;if(input)input.value='';}};
window.runScan=async function(){const button=document.getElementById('scanActionBtn'),mount=document.getElementById('qrScannerMount'),video=document.getElementById('qrScanVideo'),status=document.getElementById('scanStatus');if(!button)return;const activity=await getSelectedActivity();if(!activity){if(status)status.textContent='Open an activity first.';return;}const setStatus=(message)=>{if(status)status.textContent=message;};const stop=async()=>{if(activeHtml5Scanner){try{await activeHtml5Scanner.stop();await activeHtml5Scanner.clear();}catch{}activeHtml5Scanner=null;}if(activeScannerStream){activeScannerStream.getTracks().forEach(track=>track.stop());activeScannerStream=null;}if(mount)mount.hidden=true;if(video)video.hidden=true;button.disabled=false;button.textContent='SCAN WITH CAMERA';};window.stopActivityScanner=stop;const record=async(value)=>{const result=await submitScannedActivityQr(value,activity);setStatus(result.message);await stop();};
 if(window.Html5Qrcode){if(!navigator.mediaDevices?.getUserMedia){setStatus('Camera is unavailable. Use Import QR Image or open the app on localhost and allow camera access.');return;}try{button.disabled=true;button.textContent='SCANNING…';mount.hidden=false;setStatus('');activeHtml5Scanner=new Html5Qrcode('qrScannerMount',{formatsToSupport:[Html5QrcodeSupportedFormats.QR_CODE]});await activeHtml5Scanner.start({facingMode:'environment'},{fps:10,qrbox:(width,height)=>{const size=Math.floor(Math.min(width,height)*.94);return {width:size,height:size};}},async(decoded)=>{if(activeHtml5Scanner){try{await record(decoded);}catch(error){setStatus(error.message);await stop();}}},()=>{});const fitCamera=()=>mount.querySelectorAll('video').forEach(camera=>{camera.style.setProperty('width','100%','important');camera.style.setProperty('height','100%','important');camera.style.setProperty('max-width','none','important');camera.style.setProperty('object-fit','cover','important');});fitCamera();const layoutObserver=new MutationObserver(fitCamera);layoutObserver.observe(mount,{childList:true,subtree:true,attributes:true,attributeFilter:['style']});window.stopActivityScanner=async()=>{layoutObserver.disconnect();await stop();};return;}catch(error){await stop();setStatus('Could not start camera: '+error.message+' Check camera permission.');return;}}
 if(!('BarcodeDetector'in window)||!navigator.mediaDevices?.getUserMedia){setStatus('Camera scanner is unavailable. Use Import QR Image or check your internet connection.');return;}try{activeScannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});video.srcObject=activeScannerStream;video.hidden=false;mount.hidden=true;await video.play();button.disabled=true;button.textContent='SCANNING…';setStatus('');const detector=new BarcodeDetector({formats:['qr_code']});const scan=async()=>{if(!activeScannerStream)return;try{const codes=await detector.detect(video);if(codes.length){try{await record(codes[0].rawValue||'');}catch(error){setStatus(error.message);await stop();}}else requestAnimationFrame(scan);}catch(error){setStatus(error.message);await stop();}};requestAnimationFrame(scan);}catch(error){setStatus('Camera unavailable: '+error.message);await stop();}};
async function loadSubmissionData(){const a=await getSelectedActivity();if(!a)return;const [pending,done,people]=await Promise.all([activityRequest(`submissions&activity_id=${a.id}&status=pending`),activityRequest(`submissions&activity_id=${a.id}&status=verified`),activityRequest(`participants&activity_id=${a.id}`)]);pendingSubmissions=pending.submissions||[];renderSubmissionList('verifyListContainer',pendingSubmissions,true);renderSubmissionList('verifiedSubmissionList',done.submissions||[],false);renderParticipants(people.participants||[]);}
function renderSubmissionList(id,rows,actionable){const list=document.getElementById(id);if(!list)return;list.innerHTML='';if(!rows.length){list.innerHTML='<div class="admin-empty-subview"><h4>No submissions yet.</h4></div>';return;}rows.forEach(row=>{const card=document.createElement('div');card.className='submission-review-card';card.innerHTML=`<strong>${escapeHtml(row.name)}</strong><span>${escapeHtml(row.submission_type)} · ${escapeHtml(row.file_name)} · ${escapeHtml(row.status)}</span>${actionable?'<button type="button">REVIEW</button>':''}`;if(actionable)card.querySelector('button').onclick=()=>openSubmission(row);list.appendChild(card);});}
let activityParticipantRows=[];
function renderParticipants(rows){activityParticipantRows=rows;const body=document.getElementById('participantsTableBody');if(!body)return;body.innerHTML=rows.length?'': '<tr><td colspan="5" class="empty-table-cell">No participants yet.</td></tr>';rows.forEach(row=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${escapeHtml(row.name)}</td><td>${escapeHtml(row.barangay||'—')}</td><td>${escapeHtml(row.time_in||'—')}</td><td>${escapeHtml(row.time_out||'—')}</td><td>${escapeHtml(row.submission||'—')}</td>`;body.appendChild(tr);});}
window.exportActivityParticipants=function(){if(!activityParticipantRows.length){alert('There are no attendance records to export yet.');return;}if(!window.XLSX){alert('Excel export could not load. Refresh the page and try again.');return;}const rows=activityParticipantRows.map(row=>({'NAME':row.name||'','BARANGAY':row.barangay||'','TIME IN':row.time_in||'','TIME OUT':row.time_out||'','SUBMISSION':row.submission||'—'}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Participants');const title=(document.getElementById('participantsActivityTitle')?.textContent||'activity').replace(/[^a-z0-9-_]+/gi,'_');XLSX.writeFile(wb,`BASIS_${title}_participants.xlsx`);};
function openSubmission(row){currentSubmission=row;const view=row.submission_type==='absence'?'view-activity-verify-absence':'view-activity-verify-attendance';showSubView(view);setAll('.verify-name',row.name);const preview=document.querySelector(`#${view} .submitted-file-preview`);if(!preview)return;preview.replaceChildren();if(row.submission_type==='attendance'){const image=document.createElement('img');image.src=row.file_data;image.alt=`Attendance proof submitted by ${row.name||'user'}`;image.className='proof-image-preview';preview.appendChild(image);}else{const pdf=document.createElement('iframe');pdf.src=row.file_data;pdf.title=`Absence excuse letter submitted by ${row.name||'user'}`;pdf.className='proof-pdf-preview';preview.appendChild(pdf);}}
window.openVerifyDetail=function(t){const row=pendingSubmissions.find(s=>s.submission_type===t);if(row)openSubmission(row);else alert('No pending '+t+' submissions.');};
window.resolveVerification=async function(status){if(!currentSubmission)return;try{await activityRequest('verify',{id:currentSubmission.id,status});currentSubmission=null;await loadSubmissionData();showSubView('view-activity-verify');}catch(e){alert(e.message);}};
window.submitNewActivity=function(){document.querySelector('.create-btn')?.click();};

document.addEventListener('DOMContentLoaded',async()=>{ if(document.getElementById('adminActivityList'))renderActivityList(); if(document.getElementById('activityName'))setupCreateActivity(); if(document.getElementById('scanActionBtn'))document.getElementById('qrImportFile')?.addEventListener('change',window.importActivityQr); if(document.getElementById('scanActionBtn'))document.addEventListener('visibilitychange',()=>{if(document.hidden)window.stopActivityScanner?.();}); try{const a=await getSelectedActivity();if(a)fillActivityDetails(a);if(document.getElementById('verifyListContainer')||document.getElementById('participantsTableBody'))await loadSubmissionData();}catch(e){console.warn(e.message);} });
