/* BASIS ADMIN — ACTIVITY DATA LOGIC
   No template/sample activity data.
   Activities appear only after the admin creates one. */

const ACTIVITY_STORAGE_KEY = 'basisAdminActivities';
const SELECTED_ACTIVITY_KEY = 'basisAdminSelectedActivityId';

async function activityRequest(action, body){ const r=await fetch(`api/activity_api.php?action=${action}`,{method:body?'POST':'GET',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}); const d=await r.json(); if(!r.ok||!d.success)throw new Error(d.message||'Activity request failed.'); return d; }
async function getActivities(){ return (await activityRequest('list')).activities||[]; }
async function getSelectedActivity(){ const id=sessionStorage.getItem(SELECTED_ACTIVITY_KEY); if(!id)return null; return (await activityRequest(`get&id=${encodeURIComponent(id)}`)).activity; }
function escapeHtml(v){ return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;'); }
function formatDate(v){ if(!v)return ''; const d=new Date(v+'T00:00:00'); return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-US',{month:'2-digit',day:'2-digit',year:'numeric'}); }
function setText(id,v){ const e=document.getElementById(id); if(e)e.textContent=v||''; }
function setAll(sel,v){ document.querySelectorAll(sel).forEach(e=>e.textContent=v||''); }
function semesterLabel(a){ return [a?.academicYear||'',a?.semester||''].filter(Boolean).join(' '); }

function fillActivityDetails(a){
 if(!a)return;
 const sem=semesterLabel(a), date=formatDate(a.date), time=[a.startTime,a.endTime].filter(Boolean).join(' - '), deadline=[formatDate(a.deadlineDate),a.deadlineTime].filter(Boolean).join(' ');
 setText('detailActivityTitle',a.name); setText('detailActivityType',a.type); setText('detailSemester',sem); setText('detailDate',date); setText('detailTime',time); setText('detailVenue',a.venue); setText('detailVenueAddress',a.venueAddress); setText('detailDescription',a.description); setText('detailDeadline',deadline);
 setText('qrSemester',sem); setText('qrTitle',a.name); setText('qrType',a.type); setText('qrDate',date); setText('qrTime',time); setText('qrVenue',a.venue); setText('qrVenueAddress',a.venueAddress); setText('qrName',a.name); setText('qrMunicipality',a.municipality); setText('qrBarangay',a.barangay); setText('qrDeadline',deadline);
 const qrImage=document.getElementById('activityQrImage'); if(qrImage){const enabled=['qr','both'].includes(String(a.generateQr||a.generate_qr||'').toLowerCase());qrImage.hidden=!enabled;if(enabled)qrImage.src=`../admin/api/activity_qr.php?id=${encodeURIComponent(a.id)}`;}
 setText('submissionSemester',sem); setText('submissionDate',date); setText('submissionTime',a.deadlineTime); setText('submissionTitle',a.name); setText('submissionType',a.type); setText('submissionInfoDate',date); setText('submissionInfoTime',time); setText('submissionVenue',a.venue); setText('submissionVenueAddress',a.venueAddress); setText('submissionName',a.name); setText('submissionMunicipality',a.municipality); setText('submissionBarangay',a.barangay);
 setText('menuActivityTitle',a.name); setText('participantsActivityTitle',a.name); setText('scanActivityTitle',a.name); setText('scanSemester',sem); setText('scanDate',date); setText('scanTime',time); setText('scanVenue',a.venue); setText('scanVenueAddress',a.venueAddress); setText('scanDeadline',deadline); setText('scanDescription',a.description);
 const canQr=['qr','both'].includes(String(a.generateQr||a.generate_qr||'').toLowerCase());document.querySelectorAll('[data-requires-qr]').forEach(el=>el.hidden=!canQr);document.querySelectorAll('[data-requires-proof]').forEach(el=>el.hidden=!['proof','both'].includes(String(a.generateQr||a.generate_qr||'').toLowerCase()));
 setAll('.verify-title',a.name); setAll('.verify-sem',sem); setAll('.verify-date',date); setAll('.verify-time',time); setAll('.verify-venue',a.venue); setAll('.verify-address',a.venueAddress); setAll('.verify-name',a.name); setAll('.verify-municipality',a.municipality); setAll('.verify-barangay',a.barangay); setAll('.verify-deadline',deadline);
}

async function renderActivityList(){
 const list=document.getElementById('adminActivityList'); if(!list)return; let items=[]; try{items=await getActivities();}catch(e){list.textContent=e.message;return;} list.innerHTML='';
 if(!items.length){ list.innerHTML='<div class="admin-no-activity"><i class="fa-solid fa-book-open"></i><h3>No activities yet.</h3><p>Created activities will appear here.</p></div>'; return; }
 items.forEach(a=>{ const card=document.createElement('div'); card.className='admin-activity-card'; card.innerHTML=`<div><h3>${escapeHtml(a.name)}</h3><span>${escapeHtml(formatDate(a.date||a.activity_date))}</span></div><button class="open-activity-btn" type="button">OPEN</button>`; card.querySelector('button').onclick=()=>{sessionStorage.setItem(SELECTED_ACTIVITY_KEY,String(a.id));window.location.href='activity_menu-admin.html';}; list.appendChild(card); });
}

function setupCreateActivity(){
 const btn=document.querySelector('.create-btn'); if(!btn)return; btn.onclick=async function(e){ e.preventDefault(); const name=document.getElementById('activityName')?.value.trim()||''; if(!name){alert('Please enter an activity name.');return;} const a={name,type:document.getElementById('activityType')?.value||'',date:document.getElementById('activityDate')?.value||'',startTime:document.getElementById('activityStartTime')?.value||'',endTime:document.getElementById('activityEndTime')?.value||'',venue:document.getElementById('activityVenue')?.value.trim()||'',venueAddress:document.getElementById('activityVenueAddress')?.value.trim()||'',generateQr:document.getElementById('generateQr')?.value||'',deadlineDate:document.getElementById('activityDeadlineDate')?.value||'',deadlineTime:document.getElementById('activityDeadlineTime')?.value||'',academicYear:document.getElementById('academicYear')?.value.trim()||'',semester:document.getElementById('semester')?.value||'',description:document.getElementById('activityDescription')?.value.trim()||'',municipality:'',barangay:''}; try{const d=await activityRequest('create',a);sessionStorage.setItem(SELECTED_ACTIVITY_KEY,String(d.id));window.location.href='activity-admin.html';}catch(err){alert(err.message);} };
}

window.setSubmissionTab=function(t){const a=document.getElementById('tabAttendance'),b=document.getElementById('tabAbsence');if(!a||!b)return;a.classList.toggle('active',t==='attendance');b.classList.toggle('active',t==='absence');};
let activeScannerStream=null;
window.runScan=async function(){const button=document.getElementById('scanActionBtn'),video=document.getElementById('qrScanVideo'),status=document.getElementById('scanStatus');if(!button)return;const activity=await getSelectedActivity();if(!activity){alert('Open an activity first.');return;}const stop=()=>{if(activeScannerStream)activeScannerStream.getTracks().forEach(track=>track.stop());activeScannerStream=null;button.disabled=false;button.textContent='SCAN';if(video)video.hidden=true;};const record=async(value)=>{let body={activity_id:Number(activity.id)};if(value.startsWith('BASIS-U:'))body.user_id=Number(value.slice(8));else body.control_number=value;const result=await activityRequest('check-in',body);if(status)status.textContent=result.message;stop();};if(!('BarcodeDetector'in window)||!navigator.mediaDevices?.getUserMedia){const code=prompt('Camera QR scanning is unavailable. Enter the scholar control number:');if(code){try{await record(code.trim());}catch(e){if(status)status.textContent=e.message;}}return;}try{activeScannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});video.srcObject=activeScannerStream;video.hidden=false;await video.play();button.disabled=true;button.textContent='SCANNING...';if(status)status.textContent='Hold the scholar QR code in front of the camera.';const detector=new BarcodeDetector({formats:['qr_code']});const scan=async()=>{if(!activeScannerStream)return;try{const codes=await detector.detect(video);if(codes.length){const value=codes[0].rawValue||'';if(!value.startsWith('BASIS-U:'))throw new Error('This QR code is not a scholar code.');await record(value);}else requestAnimationFrame(scan);}catch(e){if(status)status.textContent=e.message;stop();}};requestAnimationFrame(scan);}catch(e){if(status)status.textContent='Camera unavailable: '+e.message;stop();}};
window.openVerifyDetail=function(t){showSubView(t==='attendance'?'view-activity-verify-attendance':'view-activity-verify-absence');};
window.resolveVerification=function(){showSubView('view-activity-verify');};
window.submitNewActivity=function(){document.querySelector('.create-btn')?.click();};

document.addEventListener('DOMContentLoaded',async()=>{ if(document.getElementById('adminActivityList'))renderActivityList(); if(document.getElementById('activityName'))setupCreateActivity(); if(document.getElementById('scanActionBtn')){const control=document.getElementById('manualControlNumber');document.getElementById('scanActionBtn').addEventListener('click',async()=>{if(control&&!('BarcodeDetector'in window)&&control.value)try{const a=await getSelectedActivity();await activityRequest('check-in',{activity_id:a.id,control_number:control.value.trim()});control.value='';}catch(e){document.getElementById('scanStatus').textContent=e.message;}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&activeScannerStream)activeScannerStream.getTracks().forEach(track=>track.stop());});} try{const a=await getSelectedActivity();if(a)fillActivityDetails(a);}catch(e){console.warn(e.message);} });
